name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # - name: Install Poetry
      #   run: |
      #     curl -sSL https://install.python-poetry.org | POETRY_HOME=/etc/poetry python3 -
      #     echo "PATH=/etc/poetry/bin:${PATH}" >> $GITHUB_PATH

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Project
        run: poetry install --with dev

      - name: Run pre-commmit
        run: pre-commit run --all --verbose
