# TODO: Switch to https://github.com/marketplace/actions/pypi-publish
name: Publish to Test PyPI

on:
  push:
    tags:
      - '*.*.*'

jobs:
    test-publish:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.10'

          - name: Install Poetry
            uses: snok/install-poetry@v1

          - name: Install Project
            run: poetry install --with dev

          - name: Configure Poetry
            run: |
              poetry config repositories.testpypi https://test.pypi.org/legacy/
              poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_API_KEY }}

          - name: Publish package
            run: poetry publish --build -r testpypi
